---
- hosts: all
  remote_user: root
  become: yes

  vars:
    new_mongodb_user: test_user
    new_mongodb_pass: password

  roles:
    - bbatsche.MongoDB-Install
  tasks:
    - include: tasks/main.yml
