---
- name: Create User
  bebat_mongodb_user:
    name:           "{{ new_db_user}}"
    password:       "{{ new_db_pass }}"
    login_user:     "{{ db_admin }}"
    login_password: "{{ db_pass }}"
    database:       "{{ db_name | default('admin') }}"
    state:          present
    roles:          "{{ 'root,backup,restore' if db_name|default('admin') == 'admin' else 'dbOwner' }}"
